#!/usr/bin/env bash
#this script tells a story about passwd using variables pulled from the text
while IFS= read -r line
do
USERNAME=$(echo "$line" | cut -f 1 -d ":")
GROUP_ID=$(echo "$line" | cut -f 3 -d ":")
HOME_DIRECTORY=$(echo "$line" | cut -f 6 -d ":")
COMMAND=$(echo "$line" | cut -f 7 -d ":")
USER_ID=$(echo "$line" | cut -f 4 -d ":")
PASSWORD=$(echo "$line" | cut -f 2 -d ":")
USER_ID_INFO=$(echo "$line" | cut -f 5 -d ":")

echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < "/etc/passwd"
