#!/usr/bin/env bash
#this script counts from 0 to 10, adding 1 to the variable to each loop. On the 9th loop the string changes
x=0
while [ $x -le 10 ]
do
if [ $x = 9 ]; then
echo "Hi"
else
echo "Best School"
fi
x=$((x+1))
done
