#!/usr/bin/env bash
#this script runs a while loop, adding 1 to a variable with each iteration. An if,elif statement is used to identify certain loops to change the pattern of the output
x=1
while [ $x -le 10 ]
do
if [ $x = 4 ]; then
echo "bad luck"
elif [ $x = 8 ]; then
echo "good luck"
else
echo "Best School"
fi
x=$((x+1))
done
