#!/usr/bin/env bash
#this script counts up from Hour 0 by one with each loop. Every 60 cycles it adds 1 to the hour variable and resets the minute variable.
minute=0
hour=0
echo "Hour: 0"
while [ $hour -le 12 ]
do
if [ $minute != 59 ]; then
minute=$((minute + 1))
echo "$minute"
else
hour=$((hour+1))
minute=0
echo "Hour: $hour"
fi
done
